version: '3.7'

services:
  kuzzle:
    image: kuzzleio/kuzzle:2.4.2
    restart: on-failure
    ports:
      - "7514:7512"
      - "1885:1883"
    cap_add:
      - SYS_PTRACE
    networks:
      - psychic-kuzzle-network
    depends_on:
      - redis
      - elasticsearch
    healthcheck:
      test: curl -f http://localhost:7514 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__protocols__mqtt__enabled=true
      - NODE_ENV=production

  redis:
    image: redis:5
    networks:
      - psychic-kuzzle-network

  elasticsearch:
    image: kuzzleio/elasticsearch:7.4.0
    restart: on-failure
    ulimits:
      nofile: 65536
    healthcheck:
      test: curl -f http://localhost:9200 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - "./eskuzzledata:/usr/share/elasticsearch/data" 
    networks:
      - psychic-kuzzle-network

networks:
  psychic-kuzzle-network:
    name: psychic-kuzzle-network
    driver: bridge